### ISSUE TITLE
Shorthand format for`timerFormatting`

### ISSUE THREAD

**Issue by samwalshnz** [en-japan-air/react-intl-formatted-duration#20]
Is there any chance that this package could support shorthand duration time formatting?

e.g. `4h 10m 40s`?

**Comment by piuccio** [comment]
Only partially.
Have a look at https://github.com/en-japan-air/react-intl-formatted-duration/blob/master/README.md#custom-format
The only problem is that at the moment you can only use either the standard format or your custom format globally in your whole application, because the format is defined in your localization files.

If you need both formats at the same time I can guide you to an alternative solution.

**Comment by samwalshnz** [comment]
I've had a look at the custom-format link you shared. We do need to use various formats within the apps. In some places, it needs to say `3 days`, in some `4d 20h 30m` or `4d`. Any ideas how we might be able to do this?

**Comment by piuccio** [comment]
Hey, got a bit busy recently. I opened a PR on the [core package](https://github.com/en-japan-air/intl-unofficial-duration-unit-format/pull/3) to add support for different styles.
Soon I'll review, merge and update this package to use the new code so you'll be able to use multiple styles in the same app.

**Comment by piuccio** [comment]
It took a while but you can now use `unitDisplay: 'long'` (or `short` or `narrow`) to change the display. Have a look at the [documentation](https://github.com/en-japan-air/react-intl-formatted-duration#unit-display)
