### ISSUE TITLE
textComponent without styled.span

### ISSUE THREAD

**Issue by xanderiel** [en-japan-air/react-intl-formatted-duration#9]
In the below example for React DOM, can you tell me how to _not_ use `styled.span` and instead something like `react.createElement('span', ...)` for the `textComponent` ?
Would be nice not needing to include `styled-components` just for display of _one_ duration in my project. Otherwise: _love_ this component!

```
// Using React DOM
import React from 'react';
import FormattedDuration from 'react-intl-formatted-duration';

import styled from 'styled-components';
const Text = styled.span``;

export default MyComponent() {
  return <FormattedDuration seconds={60} textComponent={Text} />
  // will render `1 minute`
}
```

**Comment by piuccio** [comment]
I haven't tried yet, but just looking at the [code](https://github.com/en-japan-air/react-intl-formatted-duration/blob/master/index.js#L26) it feels like this should work

```
<FormattedDuration seconds={60} textComponent="span" />
```

because internally the library is simply calling `React.createElement(textComponent)`

I can see from the props that it requires a function, so you'll end up with a console error in development mode. If that's the case it should be enough to update the prop validation.

If you want to get around the console error without any change in the code I guess you can always call

```
const Span = (props) => <span {...props} />;
<FormattedDuration seconds={60} textComponent={Span} />
```

**Comment by xanderiel** [comment]
Thanks @piuccio, great find. It did indeed work but throw an error. Quick and dirty solution for me right now is to just comment out that line in the module's source code.
